//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Id { get; set; }
        public bool modifiable { get; set; }
        public int answer { get; set; }
    
        public virtual Answer Answer1 { get; set; }
    }
}
