//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.DateTime created { get; set; }
        public string content { get; set; }
        public string fullname { get; set; }
        public int upvote_count { get; set; }
        public bool user_has_upvoted { get; set; }
        public Nullable<int> parent { get; set; }
        public bool createdByCurrentUser { get; set; }
        public System.DateTime modified { get; set; }
        public int vId { get; set; }
        public string uId { get; set; }
        public string cId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual VideoSery VideoSery { get; set; }
        public virtual Video Video { get; set; }
    }
}
