//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Ratings = new HashSet<Rating>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public bool paid { get; set; }
        public string URL { get; set; }
        public int videoseries { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public int section { get; set; }
        public Nullable<int> localorder { get; set; }
        public string overview { get; set; }
        public Nullable<int> views { get; set; }
    
        public virtual VideoSery VideoSery { get; set; }
        public virtual Section Section1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
